# Generated by Django 6.0.3 on 2026-03-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='acronimo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
