# Generated by Django 6.0.3 on 2026-03-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_acronimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
