# Generated by Django 6.0.3 on 2026-03-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rol_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='estadomarkup',
            options={'ordering': ['orden'], 'verbose_name': 'Estado de Markup', 'verbose_name_plural': 'Estados de Markup'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
