# Generated by Django 6.0.3 on 2026-03-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_area_options_alter_estadomarkup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMarkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tipo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Markup',
                'verbose_name_plural': 'Tipos de Markup',
            },
        ),
    ]
