# Generated by Django 6.0.3 on 2026-03-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipomarkup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['numero_empleado']},
        ),
        migrations.AlterModelOptions(
            name='tipomarkup',
            options={'ordering': ['num_tipo'], 'verbose_name': 'Tipo de Markup', 'verbose_name_plural': 'Tipos de Markup'},
        ),
    ]
