# Generated by Django 6.0.3 on 2026-03-20 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_tipomarkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nueva_revision', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='La revisión solo puede contener letras.', regex='^[a-zA-Z]*$')])),
                ('url_archivo', models.URLField(blank=True, max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_compromiso', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markups', to='core.estadomarkup')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markups', to='core.empleado')),
                ('tipo_markup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markups', to='core.tipomarkup')),
            ],
            options={
                'verbose_name': 'Markup',
                'verbose_name_plural': 'Markups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
