# Generated by Django 6.0.3 on 2026-03-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='markup',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='markup',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
